name: Setup

on:
  push:

jobs:
  build:
    if: ${{ ! endsWith(github.repository, '-template') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Build templates output
        uses: pedrolamas/handlebars-action@v1.0.4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
