name: Welcome

on:
  push:

jobs:
  build:
    if: endsWith(github.ref, '/master') && ! endsWith(github.repository, '-template')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: |
          export GITHUB_REPOSITORY_NAME=${GITHUB_REPOSITORY/*\/}

          cat README.md | envsubst `env | awk -F = '{printf "\$%s,", $1}'` > README.md
          cat package.json | envsubst `env | awk -F = '{printf "\$%s,", $1}'` > package.json

          rm .github/workflows/startup.yml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
